import type { Metadata } from "next";

// import localFont from "next/font/local";
import { auth } from "@/lib/auth";
import SessionProvider from "@/providers/SessionProvider";
import { Providers } from "@/providers/api-client-provider";
import { ThemeProvider } from "@/providers/theme-provider";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <body className={`bg-primary-foreground antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <SessionProvider session={session}>
            <Providers>{children}</Providers>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
