import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from 'sonner';
import Provider from "@/components/Provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Boilgen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
      className={cn(
        "min-h-screen font-sans",
        fontSans.variable
      )}
      >
        <ThemeProvider
        attribute="class"
        defaultTheme="white"
        // enableSystem
        disableTransitionOnChange
        >
        <Provider>
          {children}
        </Provider>
        <Toaster richColors/>
        </ThemeProvider>
        </body>
    </html>
  );
}
